### PR TITLE
Oop export

### PR DESCRIPTION
**Pull request by ltabis**
This is not mentioned in the OOP chapter, but objects cannot be exported by modules if they contain anonymous functions.
I added a warning with a few explanation and a possible way to get over it.

Edit: Because of my fork this PR also contains a CI script to check for broken links automatically, tell me if this needs to be removed.

### CODE REVIEW

**Comment by schungx** [comment]
Actually objects containing anonymous functions can be exported from modules. I fixed that a while ago.

Not sure if it is in the current release. I'll check...

**Comment by ltabis** [comment]
> EDIT: This should be live in `1.14.0`. Can you check?

Yes, it does work, my bad. I was testing it with specific usage of the object for example:
```
export const object = #{
    x: [
        || print("test1"),
        || print("test2"),
    ]
};

export const object = [
        || print("test1"),
        || print("test2"),
    ];
```
I was not working with objects, my mistake !

**Comment by ltabis** [comment]
BTW @schungx you can actually export anonymous functions using a custom implemented macro that copy the entire module script into the main script. I think it's a bad solution but it works.

**Comment by schungx** [comment]
Ah... So arrays didn't work?  They should...

**Comment by schungx** [comment]
> BTW @schungx you can actually export anonymous functions using a custom implemented macro that copy the entire module script into the main script. I think it's a bad solution but it works.

That would probably be too much if the script is too large...

**Comment by ltabis** [comment]
> Ah... So arrays didn't work? They should...

I believe they work looking back at my discord message, it's just that I was trying to execute those on the Rust side !

**Pull request closed without merging**
